### ISSUE TITLE
We're stalking you.

### ISSUE THREAD

**Issue by Nobie-git** [Grape-Boy/FNF-SoftEngine#1]
### What is your question?

You won't notice it since we won't interact with you online as much as in real life but we're cyberstalking you just so you know
![k8](https://user-images.githubusercontent.com/63230056/177424977-bcd1fc42-e2c6-44a5-88d0-335cd1daf4da.jpg)
.

**Comment by Grape-Boy** [comment]
i shouldn't have linked my github 😳
